language: go
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 4581ac38a9150ff449bc0eb23a22ec31448a07e3
  keep_history: true
  on:
    branch: master

go:
  - "1.14"
  - "stable"

services:
  - postgresql

addons:
  postgresql: "12"

env:
  global:
    - DB_URI=postgres://postgres@localhost:5432/oauth2_test?sslmode=disable

before_install:
  - psql -c 'create database oauth2_test;' -U postgres
  - env GO111MODULE=on go mod vendor

script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s http://localhost/bash)
